### PR TITLE
Create experiment for cpl_gray+swamp+ocn

### PR DESCRIPTION
**Pull request by qwert2266**
Working on creating experiment, readme is here now and will add other code later

### CODE REVIEW

**Comment by jm-c** [comment]
@qwert2266  Thanks for sharing your set-up, this is great. I will take a look in the coming days and will see if there is something to add or change.

**Comment by jm-c** [comment]
@qwert2266 I did some cleaning so that I can now compile for single-proc component (easier for testing). I still have issues to run, because the `input_ocn/data` setting of `delR` is not consistent with the rest of the set-up (Nr=15 in SIZE.h, tRef,sRef setting, size of input bin files). Could you check this ?

**Comment by jm-c** [comment]
And regarding number of procs to use to run atm & ocn as well as at which level to create the `rank_?` dir:
For now, I think it's easier to use the same convention as for the other coupled set-up, so that one can use `tools/run_cpl_test` to check that everything works.
In the future we could try to add new arguments to `run_cpl_test` so enable to change number of procs (this is already there but as hard coded parameters) and to have the rank dir one level up (but this requires also to adjust `prepare_run` in `input_*` dirs.
And for now, we would just keep a multi-proc SIZE.h version (I don't like too much the suffix ".3procs" and ".24procs" that I put there and could use soemthing else) and document this.

**Comment by qwert2266** [comment]
Hey Jean-Michel,

I updated the SIZE.h and Initiation files, sorry about that. They were from
a run that didn't have ENSO, I will commit the new ones now. I'm not sure
where the tRef settings are, could you point me to that and I'll make the
same change?

Just to clarify, you want me to change the readme so that it's clear the
default version does not have multiple processes, but leave in that there
is an option to include this?

Thanks,
PJ

**Comment by qwert2266** [comment]
Nevermind, I updated tRef and sRef

**Comment by jm-c** [comment]
@qwert2266 Thanks for the update the ocean set-up. I am going to check few other things (and may be clean-up little things) and will let you know how it goes. After that we could review the README once everything is in place.

**Pull request merged**
