### PR TITLE
Update adjoint example

### PR DESCRIPTION
**Pull request by mmazloff**
Update code_ad and input_ad
Still some recomputations but do not appear serious. Adjoint code runs successfully. 
We have removed diagnostics at run time and added generic controls and  generic cost

### CODE REVIEW

**Comment by mmazloff** [comment]
@jm-c 
just want to make sure you saw this

**Comment by jm-c** [comment]
@mmazloff I tried to run adjoint testreport (using gfortran and -devel) but it stoped at the end of first
forward part with a floating point exception (in: bling_bio_nitrogenmd ).
I also noticed many compilation warnings (conversion type) since we havei, in tamc.h:
  PARAMETER( isbyte      = 4 )
 Could you check this ?

**Comment by mmazloff** [comment]
@jm-c 
Thanks for checking this! Sorry for the issues. 

I will change to 
PARAMETER( isbyte = 8 )
Thanks for noting that!

Regarding floating point exception (in: bling_bio_nitrogenmd ): I wasn't able to reproduce this. Can you help me? I compiled with 
#    ../../../tools/genmake2 -ds -m make -mods=../code_ad -optfile=../../../tools/build_options/linux_amd64_gfortran -devel

Thanks!

**Comment by jm-c** [comment]
@mmazloff  I am using the same genmake2 command as you, on fc29 linux machine with
gfortran 8.3.1, and latest TAF version (4.3.7) ; Also, as you saw from last Friday commit, I used the same set of binary files as for the for the forward test. Is it right ?

**Comment by mmazloff** [comment]
@jm-c I upgraded to gfortran 8.3.1 and I am using the latest compiler, but I cannot reproduce this. 
Maybe it is my operating system. I am using
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.7 (Maipo)
Release:	7.7
Codename:	Maipo

I can try a different machine. What OS are you using?

**Comment by mmazloff** [comment]
@jm-c:  OH! I think I do get it. At the very end of my run it reads:

PROGRAM MAIN: Execution ended Normally
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
STOP NORMAL END

How did you know it was in bling_bio_nitrogenmd?  My run doesn't crash, so any advice on debugging this appreciated! Is there a compile flag you recommend to debug this?

**Comment by jm-c** [comment]
@mmazloff the "Note:" your are getting at the end of the run does not mean much since all experiments
(forward & adjoint) generate this "Note:" (not even a warning) when using recent version of gfortran compiler. 
Now the OS I was using for my test is Fedora 29 (I mentioned fc29 earlier); I am going to check on 
a different Linux platform to see if it works there. Will let you know.
And BTW, which platform (OS ?) are you using for your test ?

**Comment by jm-c** [comment]
@mmazloff I've just tried on baudelaire.mit.edu (fc13, version 4.4.5 of gfortran)  and I am getting similar error:
testreport: line 845:  5876 Floating point exception(core dumped) ./mitgcmuv_ad > output_adm.txt

**Comment by mmazloff** [comment]
@jm-c 
There has to be something different about our code. I just tried again with the latest MITgcm code on a different machine
CentOS release 6.10 with gfortran version 6.1.0  
and it received normal end. 
Previously I ran on 
Red Hat Enterprise Linux Server release 7.7 (Maipo) with two different versions of gfortran without issues. 

Sorry I am having issues with this!
Can email me your ad_taf_output.f file so I can make sure the code is identical?

**Comment by jm-c** [comment]
@mmazloff OK, we are good now. I am going to do a little cleaning and generate an output_adm.txt
on baudelaire.

**Comment by mmazloff** [comment]
@jm-c 
Excellent! Thank you very much!

**Comment by jm-c** [comment]
@mmazloff pkg/grdchk is compiled but it is not used. This is a problem since, for AD experiments, testreport only compare numbers from grdchk. Could you try to cook a "data.grdchk" so that we
can use testreport ? May be you could get some idea/template from tutorial_global_oce_biogeo/input_ad/data.grdchk ?

**Comment by mmazloff** [comment]
@jm-c 
Done! Let me know if these gradients are adequate regarding accuracy. 

The cost is just one profile so if perturbation is far away may not have significant impact. I will refine this data.grdchk in the future. But for now this is (I hope!) sufficient for check in!

**Comment by jm-c** [comment]
@mmazloff I could well be that I am stupid, but I don't see the file "data.grdchk". Where is it ?

**Comment by mmazloff** [comment]
@jm-c 
I forgot "git add"!
Its there now

**Comment by mmazloff** [comment]
@jm-c 
Just made small fix of it. Good to go now!

**Comment by jm-c** [comment]
@mmazloff From my point of view, this is good to be merged. Unless you want to change something,
will merge it later today.

**Comment by mmazloff** [comment]
@jm-c 
I made some minor changes. Please go ahead and merge. 
Thanks so much!

**Comment by mmazloff** [comment]
Excellent! Thanks for all your help with this!

Is the plan now to leave this here or try to merge it into the main tree?

Matt

**Pull request merged**
