### PR TITLE
update README and convert to README.md

### PR DESCRIPTION
**Pull request by gaelforget**
in both `global_oce_cs32` and `global_oce_llc90`
- update to use github `verification_other` repo rather than old `MITgcm_contrib` repo
- move README  to README.md (hopefully history conserving...)
- reformat content to markdown

### CODE REVIEW

**Comment by jm-c** [comment]
LGTM

**Comment by jm-c** [comment]
One minor thing regarding the download instructions: it might be simpler without the "mv", directly
cloning into MITgcm;
  cd MITgcm
  git clone https://github.com/MITgcm/verification_other
(then no need for: "mv verification_other MITgcm/"). We are supposed to add a README.md" file
directly in "verification_other" with similar type of instructions (but has not been done yet).

And regarding this PR itself, not clear why we have 143 commits ! @edoddridge may be could help to
sort this out ?

**Comment by edoddridge** [comment]
I'll take a look today. 

@gaelforget did you use `git filter-branch` to pull out every commit that touched these files?

**Comment by edoddridge** [comment]
Closing in favour of #4.

**Comment by gaelforget** [comment]
Had used [git-mv-with-history](https://gist.github.com/emiller/6769886) which I think I used earlier in a case where `give mv` had failed. 

Maybe this is not an issue anymore but: <https://stackoverflow.com/questions/35618507/git-sure-fire-way-to-move-rename-files-while-keeping-the-history?rq=1>

In any event, please look at PR #4, merge it, and close this one if adequate?

**Pull request closed without merging**
