### PR TITLE
Add David Ferreira cpl setup

### PR DESCRIPTION
**Pull request by jm-c**

### CODE REVIEW

**Comment by jm-c** [comment]
@dfer22 it seems that github will not let me put you as reviewer. But anyway, would be nice if you could take a look at this PR and let me know what you think. Also, would be nice to add a reference to one of your paper in the README.

**Comment by dfer22** [comment]
I looked at differences with the setups I have. Clearly my set-ups are a bit updated. I could only identify a coupled of differences.

-in code_ocn, DIC_OPTIONS.h
in some of my latest runs, I removed the WATERVAP_BUG

- similarly with, Frictional heating turned on

Both would change the solution, and the pickups won't be consistent. But would it be worth to have remarks in the README.txt that these options (which improve the solution) are available? 

In README.txt (or somewhere else) acknowledge contribution of Alexandre Pohl with calibration of CO2-ALBCO2 relationship (piece of code is in physics_driver.F, but my name appears in aim_readparms.F, might be the best place to add Alex, so not part of this request)

**Comment by jm-c** [comment]
@dfer22 I updated few files and now mention Alexandre Pohl in the README. Also added some instructions (that I adapted form exp. `cpl_aim+ocn`). I also added a reference to your J.Climate 2010 paper (for the Double-Drake, cs24, coupled config).
Please take a look at this updated README and see if it's OK with you.

Regarding the 2 updates you mentioned (`WATERVAP_BUG` and frictional heating), I would prefer to do this in a different PR.

**Comment by dfer22** [comment]
Hello Jean-Michel,
I've added the citations we discussed in the README. Cheers, David

**Comment by dfer22** [comment]
Trying again:

line 9: this paper is 2010, not 2012

Also add, this to the paragraph
"The coupled atmospheric CO2-biogeochemistry was used in
- Ferreira et al. (2018, doi:10.1029/2018GL077019) where the atmospheric CO2 is passive (no radiative effect)
- Zhu and Rose (2022, doi:10.1175/JCLI-D-21-0984.1), which uses a radiatively active CO2
"

**Comment by jm-c** [comment]
@dfer22 I've just  added the 2 citations. Unless you would like to add or change something else, will merge this PR soon,
like before the end of the week.

**Pull request merged**
