### PR TITLE
Update/clean global oce llc90

### PR DESCRIPTION
**Pull request by jm-c**
1) Clean/simplify parameter files location:
  - move un-used (in any FWD or AD exp) param files from input/ into input/unused/
  - param files which are not used in any FWD exp (but only used in some AD exp):
   move them from input/ to input_ad/
  - simplify "prepare_run" from 4 FWD input dir by removing it's own dir (misleading)
  - since local "prepare_run" is no longer linking all files from corresponding FWD input dir, 
    make a copy of few needed files.
2) Update AD experiments by bringing back the use of viscFacInAd
  - define AUTODIFF_ALLOW_VISCFACADJ (in AUTODIFF_OPTIONS.h) and
    put back viscFacInAd setting in data.autodiff ;
  - update the 4 reference AD output files (generated on engaging using 32 procs)

### CODE REVIEW

**Comment by jm-c** [comment]
@mjlosch If you know why viscFacInAd=2 has an effect in these 4 AD experiments, despite the fact that
none does specify any 3-D horizontal viscosity files, it would be very useful. Also useful to know regarding this warning:
(PID.TID 0000.0001) ** WARNING ** AUTODIFF_READPARMS: For viscFacInFw/viscFacInAd to have any effect, specify at least one of viscAh[D/Z]file

**Comment by jm-c** [comment]
OK, the  viscFacInAd=2 effect is through horizontal biharmonic (not harmonic) viscosity files (which I missed earlier).
Everything make sense.

**Comment by jm-c** [comment]
@mjlosch do you want to update the local mom_calc_visc.F  ? otherwise I can do it and push it there, not a big deal. Thanks.

**Review by mjlosch — COMMENTED** [review]
Looks all good to me. Do you want to keep SOLVE_DIAGONAL_KINNER defined for this experiment? It leads to 6 more recomputation warnings a slightly slower code (in my case about 100s per run).

**Comment by jm-c** [comment]
> Looks all good to me. Do you want to keep SOLVE_DIAGONAL_KINNER defined for this experiment? It leads to 6 more recomputation warnings a slightly slower code (in my case about 100s per run).

I would prefer to restrict the change of results to just a post PR #384 update/fix (just viscFacInAd=2). And also not sure that we really want to drop this SOLVE_DIAGONAL_KINNER here but could discuss this afterward (and if to be done, will be in an other PR).

**Comment by mjlosch** [comment]
OK, agreed, just for the records here are my results with SOLVE_DIAGONAL_KINNER defined
```
Y Y Y Y 14>16< 1 pass  global_oce_llc90  (e=0, w=48)
Y Y Y Y 16>16< 2 pass  global_oce_llc90.core2
Y Y Y Y 16>16<16 pass  global_oce_llc90.ecco_v4
Y Y Y Y 13>16< 6 pass  global_oce_llc90.ecmwf
Start time:  Wed Feb  3 10:07:42 CET 2021
End time:    Wed Feb  3 13:20:30 CET 2021
```
 and without
```
Y Y Y Y 14>16< 5 pass  global_oce_llc90  (e=0, w=42)
Y Y Y Y 16>16< 2 pass  global_oce_llc90.core2
Y Y Y Y  9>16< 0 pass  global_oce_llc90.ecco_v4
Y Y Y Y 13>16< 6 pass  global_oce_llc90.ecmwf
Start time:  Wed Feb  3 13:42:47 CET 2021
End time:    Wed Feb  3 16:46:43 CET 2021
```
not so different in time (just 10min faster), adjoint OK, FD gradients are weird.

**Comment by jm-c** [comment]
@mjlosch To finish with this PR, going to make a new tag (checkpoint67v) soon and would be nice to have this PR merged-in
since it's a bit a follow up on PR #384. So if it's OK, will try to merge it (without #undef SOLVE_DIAGONAL_KINNER) soon.
I still need to update the "update_history" file before that.

**Comment by mjlosch** [comment]
@jm-c 
je suis d'accord. Go ahead.

**Pull request merged**
